### ISSUE TITLE
How to check if key exists?

### ISSUE THREAD

**Issue by TheTechRobo** [rhysd/tinyjson#3]
My JSON file might not contain a certain key. How do I check if such key exists? I'd rather not resort to catching panics.

**Comment by TheTechRobo** [comment]
Something similar to Python's `.get()` method would be nice. Or a HashMap's `.contains_key()` method.

**Comment by rhysd** [comment]
tinyjson represents JSON object as `HashMap<String, JsonValue>`.

```rust
let json_value: JsonValue = ...;
let maybe_object = json_value.get::<HashMap<_, _>>();
let object = maybe_object.unwrap();
let has_key_foo = object.contains_key("foo");
```

**Comment by TheTechRobo** [comment]
How do I check if it's null?

**Comment by TheTechRobo** [comment]
Nevermind, `.is_null()`

**Comment by TheTechRobo** [comment]
Thanks so much for helping, @rhysd!

**Comment by fkrauthan** [comment]
@rhysd any chance to add an easy API method to do this? The workaround is a bit verbose.

**Comment by rhysd** [comment]
Basic idea of this crate is using standard containers like `Vec` or `HashMap` as much as possible. It brings some benefits:

- This crate provides API to conversion between `JsonValue` and the containers. It makes API much simpler and users can operate JSON values via standard containers
- Users don't need to understand dedicated APIs only for modifying/accessing JSON values.
- 'Easy' APIs are usually implicit. For example, we would be able to make an API to insert new key/value pair to JSON object. But it would hide memory allocation under the hood. Explicit memory allocation is better IMHO.
- If you don't want to repeat some explicit operations, defining some small helper function would be useful and sufficient in most cases. For example, when you want to know `JsonObject` has key or not easily,
  ```rust
  fn has_key(v: &JsonValue, key: &str) -> bool {
      v.get::<HashMap<_, _>>().map(|m| m.contains(key)).unwrap_or(false)
  }
  ```

If you still want some easy APIs out of box, there are several other crates which offers such APIs. Since tinyjson has only very simple APIs, replacing it with some other crate should be easy.

**Comment by fkrauthan** [comment]
That totally makes sense. However I feel like an api to check if a key or index exists is still very minimal but would however make this library so much easier to use without having to always unpack a JsonValue as HashMap just to check if I can access a key

**Comment by TheTechRobo** [comment]
@fkrauthan I do understand rhysd's point, though - doing that might take up a lot of RAM and you might never notice the problem if you're using an abstracted API.

**Comment by fkrauthan** [comment]
But does it really take more ram? Given internally he already has the hashmap?

**Comment by fkrauthan** [comment]
So to me two helper methods on JsonValue `contains_key` and `contains_index` that in case the JsonValue is not an Object or Not a Vec/Array returns false and in other cases just uses the already present HashMap and Vec to call the respective contains method shouldn't require any additional memory allocation and should be a pretty simple method enhancement unless I am missing something.

**Comment by TheTechRobo** [comment]
Right, it's a hashmap internally. Ignore what I just said :-)

**Comment by fkrauthan** [comment]
I guess for the time being this works:

```rust
use tinyjson::JsonValue;

pub trait JsonValueExt {
    fn contains_key(&self, key: &str) -> bool;
    fn contains_index(&self, index: u8) -> bool;
}

impl JsonValueExt for JsonValue {
    fn contains_key(&self, key: &str) -> bool {
        match self {
            JsonValue::Object(obj) => obj.contains_key(key),
            _ => false,
        }
    }

    fn contains_index(&self, index: usize) -> bool {
        match self {
            JsonValue::Array(array) => array.len() > index,
            _ => false,
        }
    }
}
```

**Comment by rhysd** [comment]
Thanks for the discussion. As @fkrauthan, regarding to checking keys, it does not consume any RAM (I mentioned RAM usage as general discussion).

I will consider some query API to get elements of object or array without panic. At first I wonder if `std::ops::Index` can return `Option<JsonValue>` instead of panic, but it only allows a reference so it was not possible. I think we need separate API.

**Comment by rhysd** [comment]
I created #10. Please leave some comments if you have some thoughts.
